version: '3'
services:
  blog-auth:
    container_name: blog-auth
    build:
      context: ./blog-auth
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    depends_on:
      - blog-user
    networks:
      - 1panel-network

  blog-gateway:
    container_name: blog-gateway
    build:
      context: ./blog-gateway
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    networks:
      - 1panel-network

  blog-article:
    container_name: blog-article-service
    build:
      context: ./blog-article
      dockerfile: Dockerfile
    ports:
      - "11111:11111"
    depends_on:
      - blog-comment
      - blog-user
    networks:
      - 1panel-network

  blog-comment:
    container_name: blog-comment-service
    build:
      context: ./blog-comment
      dockerfile: Dockerfile
    ports:
      - "12221:12221"
    networks:
      - 1panel-network

  blog-user:
    container_name: blog-user-service
    build:
      context: ./blog-user
      dockerfile: Dockerfile
    ports:
      - "10001:10001"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true