server:
  port: 9999

spring:
  application:
    name: gateway-service

  cloud:
    nacos:
      server-addr: nacos:8848
      username: nacos
      password: nacos
      discovery:
        group: DEFAULT_GROUP
      config:
        group: DEFAULT_GROUP
    gateway:
      routes:
        ## user-service 服务
        - id: user-admin-api # 路由的编号
          uri: lb://user-service
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/user/**
        - id: user-app-api # 路由的编号
          uri: lb://user-service
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/user/**

        ## comment-server 服务
        - id: comment-admin-api # 路由的编号
          uri: lb://comment-service
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/comment/**
        - id: comment-app-api # 路由的编号
          uri: lb://comment-service
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/comment/**

        ## article-server 服务
        - id: article-admin-api # 路由的编号
          uri: lb://article-service
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/article/**
        - id: article-app-api # 路由的编号
          uri: lb://article-service
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/article/**
