spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8    # jdbc:mysql://47.108.209.62:3306/myweb?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: '12345678'
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379  # 端口
    password: redis6
    database: 0  # 数据库索引
    lettuce:
      pool:
        max-active: 50  # 最大连接数
        max-wait: 3000  # 最大阻塞等待时间
        max-idle: 20  # 最大空闲连接
        min-idle: 2  # 最小空间连接
    timeout: 60000 # 连接超时时间（毫秒）

#mybatis-plus:
#  mapper-locations: classpath:com/mrqinzh/**/*.xml
#  type-aliases-package: com.mrqinzh.common.entity
#  global-config:
#    db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#    banner: false
#  configuration:
#    map-underscore-to-camel-case: true
